export const refs = {
  inputRef: document.querySelector('.search__input'),
  formRef: document.querySelector('#search-form'),
  openModalCard: document.querySelector('[data-modal-open]'),
  closeModalBtn: document.querySelector('[data-modal-close]'),
  modalFilm: document.querySelector('[data-modal]'),
  body: document.querySelector('body'),
  backdrop: document.querySelector('.backdrop'),

  modalFooter: document.querySelector('[data-footer-modal]'),
  closeModalFooterBtn: document.querySelector('[data-modal-footer-close]'),
  students: document.querySelector('.students'),
  footerBtn: document.querySelector('.footer-btn'),
  backdropFooter: document.querySelector('.backdrop-footer'),
  slider: document.querySelector('.splide__list'),
  sliderModal: document.querySelector('[data-modal-open-slider]'),
  backdropSlider: document.querySelector('.backdrop-slider'),
  closeModalSliderBtn: document.querySelector('[data-modal-close-slider]'),
  trailerBtn: document.querySelector('.trailer-btn'),
  openModalAuthBtn: document.querySelector('[data-open-modal]'),
  signOutBtn: document.querySelector('[data-sign-out]'),
  sigInGoogleBtn: document.querySelector('[data-sigin-google]'),
  modal: document.querySelector('[data-modal-auth]'),
  body: document.querySelector('body'),
  closeModalAuthBtn: document.querySelector('[data-modal-auth-close]'),
  userInfo: document.querySelector('.heder_auth_info'),
  authSwitchLinks: document.querySelectorAll('.switch'),
  authModals: document.querySelectorAll('.auth .modal-auth'),
  authWrapper: document.querySelector('.auth'),
  registerForm: document.querySelector('.register'),
  loginForm: document.querySelector('.login'),

  openModalAuthBtn: document.querySelector('[data-open-modal]'),
  signOutBtn: document.querySelector('[data-sign-out]'),
  sigInGoogleBtn: document.querySelector('[data-sigin-google]'),
  modal: document.querySelector('[data-modal-auth]'),
  body: document.querySelector('body'),
  closeModalAuthBtn: document.querySelector('[data-modal-auth-close]'),
  userInfo: document.querySelector('.heder_auth_info'),
  authSwitchLinks: document.querySelectorAll('.switch'),
  authModals: document.querySelectorAll('.auth .modal-auth'),
  authWrapper: document.querySelector('.auth'),
  registerForm: document.querySelector('.register'),
  loginForm: document.querySelector('.login'),
};
